web:
  command: bundle exec rails server -p 5000 -b 0.0.0.0
  proxy:
    domains:
      - auth.compose.devkit

defaults:
  volumes:
    - ./:/app:rw
  expose:
    - 5000
  environment:
    MONGO_URL: mongodb://<%= Devkit.docker_machine.ip %>/authful
  hooks:
    start:
      pre:
        - bundle install --jobs 5
