# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

# Middleman, of course
gem 'middleman', '~>3.2.2'

# Slim templating
gem 'slim', '~> 2.0'

# Auto-prefixing plugin
gem 'middleman-autoprefixer'

# ImageOptim plugin
gem 'middleman-imageoptim', '~> 0.1.4'

# Live-reloading plugin
gem 'middleman-livereload', '~> 3.1.0'